version: '3.8'

# Definimos la red interna para que los contenedores se hablen entre sí de forma segura
networks:
  red_interna_proyecto:
    driver: bridge

services:
  # 1. BASE DE DATOS
  db:
    image: mysql:8.0
    container_name: db_mysql
    restart: always
    # SIN PORTS: Solo accesible internamente por el backend (Seguridad)
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proyecto_semestral
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql_init:/docker-entrypoint-initdb.d
    networks:
      - red_interna_proyecto
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # 2. BACKEND
  backend:
    # CORRECCIÓN: Usuario 'cristianjimenez7'
    image: cristianjimenez7/proyecto-backend:latest
    container_name: backend_app
    restart: always
    ports:
      - "8031:8080" # Puerto Pacheco (8031) -> Puerto SpringBoot (8080)
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red_interna_proyecto

  # 3. FRONTEND
  frontend:
    # CORRECCIÓN: Usuario 'cristianjimenez7'
    image: cristianjimenez7/proyecto-frontend:latest
    container_name: frontend_app
    restart: always
    ports:
      - "8028:80" # Puerto Pacheco (8028) -> Puerto Nginx (80)
    depends_on:
      - backend
    networks:
      - red_interna_proyecto

volumes:
  db_data: